blog/urls.py
# blog\urls.py ГЛАВНЫЙ
from django.contrib import admin
from django.urls import path
from python_blog.views import main, about
from django.urls import include

from django.conf import settings
from django.conf.urls.static import static
"""
Конверторы путей Django:
str - строки, любые символы кроме слэша '/' (по умолчанию)
int - положительные целые числа включая 0
slug - ASCII буквы/цифры, дефисы и подчеркивания
uuid - уникальные идентификаторы UUID пример '075194d3-6885-417e-a8a8-6c931e272f00'
path - строки, включая слэши '/'

Пример использования:
path('articles/<int:year>/', views.year_archive)
path('blog/<slug:post_slug>/', views.post_detail)

"""
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", main, name="main"),
    path("about/", about, name="about"),

    # Подключаем python_blog.urls
    path('posts/', include('python_blog.urls'), name='posts'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]

python_blog/urls.py
# python_blog\urls.py Django APP python_blog
from django.contrib import admin
from django.urls import path
from python_blog.views import catalog_posts, post_detail, catalog_categories, category_detail, catalog_tags, tag_detail

app_name = 'blog'


# Общий префикс posts/
urlpatterns = [
    # Каталог  постов posts/
    path('', catalog_posts, name='posts'),
    
    # Категории
    # Категории posts/categories/
    # Категории posts/categories/python/
    path('categories/', catalog_categories, name='categories'),
    path('categories/<slug:category_slug>/', category_detail, name='category_detail'),
    
    # Теги posts/tags/
    # Теги posts/tags/python/
    path('tags/', catalog_tags, name='tags'),
    path('tags/<slug:tag_slug>/', tag_detail, name='tag_detail'),
    
    
    path('<slug:post_slug>/', post_detail, name='post_detail'),
]

python_blog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model
from unidecode import unidecode
from django.utils.text import slugify

class Tag(models.Model):
    name = models.CharField(max_length=200, verbose_name="Название")
    slug = models.SlugField(max_length=250, unique=True, verbose_name="Слаг")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("blog:tag_detail", args=[self.slug])

    def save(self, *args, **kwargs):
        self.slug = slugify(unidecode(self.name))
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "Тег"
        verbose_name_plural = "Теги"
        ordering = ["name"]

class Post(models.Model):
    title = models.CharField(max_length=100, verbose_name="Заголовок")
    content = models.TextField(verbose_name='Контент')
    slug = models.SlugField(max_length=250, unique=True, verbose_name="Слаг", blank=True, null=True)
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name="Автор", related_name="posts", default=None, null=True)
    tags = models.ManyToManyField("Tag", related_name="posts", verbose_name="Теги")
    published_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    views = models.PositiveIntegerField(default=0, verbose_name="Просмотры")
    category = models.ForeignKey(
        "Category",
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name="posts",
        default=None,
        verbose_name="Категория",
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:post_detail", args=[self.slug])

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(unidecode(self.title))
        super().save(*args, **kwargs)

    class Meta:
        ordering = ["-published_date"]
        verbose_name = "Пост"
        verbose_name_plural = "Посты"

class Category(models.Model):
    name = models.CharField(max_length=200, verbose_name="Название")
    slug = models.SlugField(max_length=250, unique=True, verbose_name="Слаг")
    description = models.TextField(
        blank=True, null=True, default="Без описания", verbose_name="Описание"
    )

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("blog:category_detail", args=[self.slug])
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(unidecode(self.name))
        super().save(*args, **kwargs)
    
    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"
        ordering = ["name"]

python_blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.urls import reverse
from django.db.models import Count, F, Q
from django.core.paginator import Paginator

from posts_dataset import dataset
from help_functions import python_slugify, python_slugify_list

from python_blog.models import Post, Category, Tag

CATEGORIES = [
    {"slug": "python", "name": "Python"},
    {"slug": "django", "name": "Django"},
    {"slug": "postgresql", "name": "PostgreSQL"},
    {"slug": "docker", "name": "Docker"},
    {"slug": "linux", "name": "Linux"},
]


def main(request):

    context = {
        "title": "Главная страница",
        "text": "Текст главной страницы",
        "user_status": "moderator",
    }
    return render(request, "main.html", context)


def about(request):
    context = {
        "title": "О проекте",
        "project_information": "Информация о проекте",
        "contact": "Контактные данные",
    }

    return render(request, "about.html", context)


def catalog_posts(request):
    posts = (
        Post.objects.select_related("category", "author")
        .prefetch_related("tags")
        .all()
    )

    search_query = request.GET.get("search_query", "")

    if search_query:
        q_object = Q()

        if request.GET.get("search_text") == "1":
            q_object |= Q(content__icontains=search_query)

        if request.GET.get("search_title") == "1":
            q_object |= Q(title__icontains=search_query)

        if request.GET.get("search_tags") == "1":
            q_object |= Q(tags__name__icontains=search_query)

        if request.GET.get("search_category") == "1":
            q_object |= Q(category__name__icontains=search_query)

        if request.GET.get("search_slug") == "1":
            q_object |= Q(slug__icontains=search_query)

        if q_object:
            posts = posts.filter(q_object).distinct()

    sort_by = request.GET.get("sort_by", "created_date")

    if sort_by == "views":
        posts = posts.order_by("-views")
    elif sort_by == "updated_date":
        posts = posts.order_by("-updated_date")
    elif sort_by == "created_date":
        posts = posts.order_by("-published_date")

    paginator = Paginator(posts, 5)

    page_number = request.GET.get("page", 1)

    page_obj = paginator.get_page(page_number)

    context = {
        "title": "Каталог постов",
        "posts": page_obj,
    }
    
    return render(request, "catalog_posts.html", context)


def post_detail(request, post_slug):
    post = Post.objects.select_related("category", "author").prefetch_related("tags").get(slug=post_slug)

    session = request.session
    key = f"viewed_posts_{post.id}"

    if key not in session:
        Post.objects.filter(id=post.id).update(views=F("views") + 1)
        session[key] = True
        post.refresh_from_db()

    context = {
        "post": post,
        }
    return render(request, "post_detail.html", context)


def catalog_categories(request):
    context = {
        "title": "Категории",
        "categories": Category.objects.annotate(posts_count=Count("posts")).order_by("-posts_count")
    }
    return render(request, "catalog_categories.html", context)


def category_detail(request, category_slug):
    category = Category.objects.get(slug=category_slug)
    posts = category.posts.select_related('category', 'author').prefetch_related('tags').all()

    context = {
        "category": category,
        "posts": posts,
    }

    return render(request, "category_detail.html", context)


def catalog_tags(request):
    context = {
        'title': 'Теги',
        'tags': Tag.objects.annotate(posts_count=Count("posts")).order_by("-posts_count")
    }

    return render(request, "catalog_tags.html", context)


def tag_detail(request, tag_slug):
    tag = Tag.objects.get(slug=tag_slug)
    posts = tag.posts.select_related('category', 'author').prefetch_related('tags').all()

    context = {
        "title": f"Посты по тегу {tag.name}",
        "tag": tag,
        "posts": posts,
    }

    return render(request, "tag_detail.html", context)

python_blog/templates/blog.html
{% extends "base.html" %}

{% block title %}
{{title}}
{% endblock title %}

python_blog/templates/catalog_categories.html
{% extends "base.html" %}

{% block title %}
{{title}}
{% endblock title %}

{% block content %}
<h3>{{title}}</h3>
<div class="gallery">
    {% for category in categories %}
    <div class="category">
        <a href="{% url "blog:category_detail" category.slug %}">{{category.name}} ({{category.posts.count}})</a>
    </div>
    {% endfor %}
</div>
{% endblock content %}

python_blog/templates/catalog_posts.html
{% extends "base.html" %}

{% block title %}
{{title}}
{% endblock title %}

{% block content %}

<form method="GET" action="{% url "blog:posts" %}">
    <div>
        <input type="text" name="search_query" placeholder="Поиск по блогу..." value="{{ request.GET.search_query|default:'' }}">
        <button type="submit">Искать</button>
    </div>

    <div>
        Критерии поиска:
        <input type="checkbox" name="search_text" id="search_text" value='1' {% if request.GET.search_text == '1' or not request.GET.search_title %}checked{% endif %}>
        <label for="search_text">Искать в тексте</label>
        <input type="checkbox" name="search_title" id="search_title" value='1' {% if request.GET.search_title == '1' %}checked{% endif %}>
        <label for="search_title">Искать в заголовках<label>
    </div>

    <div>
        Сортировать:
        <input type="radio" name="sort_by" id="sort_created" value="created_date" {% if request.GET.sort_by == "created_date" or not request.GET.sort_by  %}checked{% endif %}>
        <label for="sort_created">По дате создания</label>
        <input type="radio" name="sort_by" id="sort_updated" value="updated_date" {% if request.GET.sort_by == "updated_date" %}checked{% endif %}>
        <label for="sort_updated">По дате обновления</label>
        <input type="radio" name="sort_by" id="sort_views" value="views" {% if request.GET.sort_by == "views"%}checked{% endif %}>
        <label for="sort_views">По количеству просмотров</label>
    </div>
</form>

{% include "post_preview_include.html" %}

{% if posts.has_previous %}
    <a href="?page={{ posts.previous_page_number }}"> <= Предыдущая</a> <br>
{% endif %}
{% if posts.has_next %}
    <a href="?page={{ posts.next_page_number }}">Следующая => </a>
{% endif %}
<br>

{% endblock content %}

python_blog/templates/catalog_tags.html
{% extends "base.html" %}

{% block title %}
{{title}}
{% endblock title %}

{% block content %}
<h3>{{title}}</h3>
<div class="gallery">
    {% for tag in tags %}
    <div class="tag">
        <a href="{% url "blog:tag_detail" tag.slug %}">#{{tag.name}} ({{tag.posts.count}})</a>
    </div>
    {% endfor %}
</div>
{% endblock content %}

python_blog/templates/category_detail.html
{% extends "base.html" %}

{% block title %}
{{category.name}}
{% endblock title %}

{% block content %}
<h3>Категория {{category.name}}</h3>
<div class="descr">{{category.description}}</div>
{% include "post_preview_include.html" %}
{% endblock content %}

python_blog/templates/menu_include.html
<nav>
    <ul>
        {% for item in menu_items %}
            <li>
                <a href="{% url item.url_name %}">{{ item.title }}</a>
            </li>
        {% endfor %}
    </ul>
</nav>

python_blog/templates/post_detail.html
{% extends "base.html" %}

{% block title %}
{{post.title}}
{% endblock title %}

{% block content %}
<div class="post_gallery">
    <div class="post">
        <h1>{{post.title}}</h1>

        <p class="tags">
            {% for tag in post.tags.all %}
            <a href="{% url "blog:tag_detail" tag.slug %}">#{{tag}}</a>
            {% endfor %}
        </p>

        <p>{{post.content}}</p>
        <p>Просмотры: {{post.views}}</p>
        <p>Категория: <a href="{% url "blog:category_detail" post.category.slug %}">{{post.category.name}}</a></p>
    </div>      
</div>

{% endblock content %}

python_blog/templates/post_preview_include.html
{% load filters %}
<div class="post_gallery">
{% for post in posts %}
    <div class="short_post">
        <h3><a href="{% url 'blog:post_detail' post.slug %}">{{ post.title }}</a></h3>
        <p>
            {% for tag in post.tags.all %}
            <a href="{% url "blog:tag_detail" tag.slug %}">#{{tag}}</a>
            {% endfor %}
        </p>
        <div>{{ post.content|truncatewords:10 }}</div>
        <p>Просмотры: {{post.views}}</p>
        <p>Категория: <a href="{% url "blog:category_detail" post.category.slug %}">{{post.category.name}}</a></p>
    </div>
    {% empty %}
    <p>Посты не найдены.</p>
{% endfor %}
</div>

python_blog/templates/tag_detail.html
{% extends "base.html" %}

{% block title %}
{{title}}
{% endblock title %}

{% block content %}
<h3>Посты по тегу {{tag.slug}}</h3>
{% include "post_preview_include.html" %}
{% endblock content %}

templates/about.html
{% extends "base.html" %}

{% block title %}
{{title}}
{% endblock title %}

{% block content %}
<p>
    {{project_information}}
</p>
<p>
    {{contact}}
</p>
{% endblock content %}

templates/base.html
{% comment %} ./base.html Базовый шаблон для всего проекта {% endcomment %}
{% load static %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Базовый шаблон. Блок title -->
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="icon" type="image/png" href="{% static 'images/favicon.png' %}">
    {% block head %}{% endblock %}
  </head>
  <body>
    <header>
      {% comment %} Будет подключатся menu_include.html {% endcomment %}
      {% include 'menu_include.html' %}
    </header>
     <!-- Базовый шаблон. Блок main -->
    <main>{% block content %} {% endblock %}</main>
    <!-- Базовый шаблон. Блок main -->
    <footer>
      {% block footer %} Все права защищены. Python422. Академия Топ. 2025 г. {%endblock %}
    </footer>
    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>

templates/main.html
{% extends "base.html" %}

{% block title %}
{{ title }}
{% endblock %}

{% block content %}
<!-- main.html  шаблон. Блок content -->
    {% comment %} Оставим HTML коммент {% endcomment %}
    {# Это Django коммент #}
    <!-- Это HTML коммент -->
    <h1>{{ title }}</h1>
    <p>{{ text|cut:"главной"}}</p>
    <hr>
   {% comment %} Условия в шаблонизаторе Django {% endcomment %}
{% if  user_status == "admin" %}
<p>Здравствуй Админ!</p>
{% elif user_status == "moderator" %}
<p>Здравствуй модератор!</p>
{% else %}
<p>Здравствуй смертный!</p>
{% endif %}

{% comment %} Проверка на вхождение в перечень {% endcomment %}

{% if user_status in "admin moderator editor" %}
    <p>У вас есть права на редактирование</p>
{% endif %}

<p>{{group|default:"Без группы"}}</p>

{% endblock %}